# Generated by Django 5.0.3 on 2024-03-23 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='watchedAt',
        ),
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='chatID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chats.chat'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChatUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.chat')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchedAt', models.DateTimeField(auto_now_add=True)),
                ('messageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.message')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
