# Generated by Django 5.0.3 on 2024-03-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_message_watchedat_chat_name_message_chatid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='messageId',
        ),
    ]
